# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            extension: 
          - os: windows-latest
            name: windows
            extension: .exe
          - os: macos-latest
            name: macos
            extension: .app.zip

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Make package (windows)
      run: |
        pyinstaller -w -F LANDrop/main.py -i LANDrop/icons/app.ico -n LANDrop --hidden-import _cffi_backend
      if: matrix.os == 'windows-latest'
    - name: Make package (linux)
      run: |
        pyinstaller -F LANDrop/main.py -n LANDrop --hidden-import _cffi_backend
      if: matrix.os == 'ubuntu-latest'
    - name: Make package (macos)
      run: |
        pyinstaller -w -F LANDrop/main.py -i LANDrop/icons/app.icns -n LANDrop --hidden-import _cffi_backend
      if: matrix.os == 'macos-latest'
    - name: Package
      working-directory: "./dist"
      run: |
        zip -r9 --symlinks LANDrop.app.zip LANDrop.app
      if: matrix.os == 'macos-latest'
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: LANDrop_${{ matrix.name }}
        path: dist/LANDrop${{ matrix.extension }}
    - name: Get version from tag
      id: extract_version
      run: |
        echo ::set-output name=version::${GITHUB_REF_NAME#v}
      shell: bash
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/LANDrop${{ matrix.extension }}
        tag: ${{ github.ref_name }}
        asset_name: LANDrop-${{ steps.extract_version.outputs.version }}-${{ matrix.name }}-x64${{ matrix.extension }}
        body: |
          PyLANDrop ${{ github.ref_name }}
          
          You can get it from [PyPI](https://pypi.org/project/LANDrop/)
      if: startsWith(github.ref_name, 'v') && github.ref_type == 'tag'
  
